### ISSUE TITLE
Indicate to the user when the query syntax is incorrect

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#111]
The backend behaviour when we encounter such queries is to perform it with Lucene's reserved characters escaped.

It would be good to have some feedback in the endpoints that accept a query parameter that the browser can then display.

**Comment by oganm** [comment]
Is there an indicator of incorrect query syntax in the output? Bad filters return 400s but was able to get 500 related to https://github.com/PavlidisLab/Gemma/issues/1225 when testing for bad queries

**Comment by arteymix** [comment]
Bad queries are usually escaped, so there's no error surfacing to the user.

For 500, these are bugs.

**Comment by oganm** [comment]
Then doing this on Gembrow side will need a specification for what is allowable in the query. Where would that be?

**Comment by arteymix** [comment]
I'm thinking of adding some warnings in the payload that GemBrow can then parse.

```yaml
data: [...]
query: '"test'
warnings: 
  - message: 'Invalid query syntax: quote is not closed, query was parsed as \"test.'
    for: query
```

I think it can be generalized whenever we notice something wrong with the request, but not bad enough to produce an HTTP error.
